### ISSUE TITLE
Font does not load when saving to files

### ISSUE THREAD

**Issue by tinarskii** [narze/ophtusify#1]
# Expected Behaviour
- Font should be loaded when images are saved to files

# Actual Behaviour
- When downloaded, they're falling back to default font instead of Prompt font

# Image when download
![ophtusify](https://user-images.githubusercontent.com/68820538/168122213-f00dd202-bc85-48c0-b1b9-2ffab4492758.png)

**Comment by narze** [comment]
just fixed

**Comment by tinarskii** [comment]
เร็วจัด
